version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/app
hooks:
  BeforeInstall:
    - location: scripts/hooks/BeforeInstall/pull_image.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/hooks/AfterInstall/restart_container.sh
      timeout: 300
      runas: ec2-user

